- name: Install Docker on EC2
  hosts: ec2
  become: true  # Run tasks as root

  tasks:
    - name: Update package lists
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - docker
          - python3
          - python3-pip
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
